// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xuwachannel_accelerator.h"

extern XUwachannel_accelerator_Config XUwachannel_accelerator_ConfigTable[];

XUwachannel_accelerator_Config *XUwachannel_accelerator_LookupConfig(u16 DeviceId) {
	XUwachannel_accelerator_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XUWACHANNEL_ACCELERATOR_NUM_INSTANCES; Index++) {
		if (XUwachannel_accelerator_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XUwachannel_accelerator_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XUwachannel_accelerator_Initialize(XUwachannel_accelerator *InstancePtr, u16 DeviceId) {
	XUwachannel_accelerator_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XUwachannel_accelerator_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XUwachannel_accelerator_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

