// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xuwachannel_accelerator.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XUwachannel_accelerator_CfgInitialize(XUwachannel_accelerator *InstancePtr, XUwachannel_accelerator_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Uwachannel_ctrl_BaseAddress = ConfigPtr->Uwachannel_ctrl_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XUwachannel_accelerator_Start(XUwachannel_accelerator *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XUwachannel_accelerator_ReadReg(InstancePtr->Uwachannel_ctrl_BaseAddress, XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_AP_CTRL) & 0x80;
    XUwachannel_accelerator_WriteReg(InstancePtr->Uwachannel_ctrl_BaseAddress, XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_AP_CTRL, Data | 0x01);
}

u32 XUwachannel_accelerator_IsDone(XUwachannel_accelerator *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XUwachannel_accelerator_ReadReg(InstancePtr->Uwachannel_ctrl_BaseAddress, XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XUwachannel_accelerator_IsIdle(XUwachannel_accelerator *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XUwachannel_accelerator_ReadReg(InstancePtr->Uwachannel_ctrl_BaseAddress, XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XUwachannel_accelerator_IsReady(XUwachannel_accelerator *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XUwachannel_accelerator_ReadReg(InstancePtr->Uwachannel_ctrl_BaseAddress, XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XUwachannel_accelerator_EnableAutoRestart(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XUwachannel_accelerator_WriteReg(InstancePtr->Uwachannel_ctrl_BaseAddress, XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_AP_CTRL, 0x80);
}

void XUwachannel_accelerator_DisableAutoRestart(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XUwachannel_accelerator_WriteReg(InstancePtr->Uwachannel_ctrl_BaseAddress, XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_AP_CTRL, 0);
}

u32 XUwachannel_accelerator_Get_c_re_1_0_V_BaseAddress(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_0_V_BASE);
}

u32 XUwachannel_accelerator_Get_c_re_1_0_V_HighAddress(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_0_V_HIGH);
}

u32 XUwachannel_accelerator_Get_c_re_1_0_V_TotalBytes(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_0_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_0_V_BASE + 1);
}

u32 XUwachannel_accelerator_Get_c_re_1_0_V_BitWidth(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_WIDTH_C_RE_1_0_V;
}

u32 XUwachannel_accelerator_Get_c_re_1_0_V_Depth(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_DEPTH_C_RE_1_0_V;
}

u32 XUwachannel_accelerator_Write_c_re_1_0_V_Words(XUwachannel_accelerator *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_0_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_0_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_0_V_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XUwachannel_accelerator_Read_c_re_1_0_V_Words(XUwachannel_accelerator *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_0_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_0_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_0_V_BASE + (offset + i)*4);
    }
    return length;
}

u32 XUwachannel_accelerator_Write_c_re_1_0_V_Bytes(XUwachannel_accelerator *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_0_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_0_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_0_V_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XUwachannel_accelerator_Read_c_re_1_0_V_Bytes(XUwachannel_accelerator *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_0_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_0_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_0_V_BASE + offset + i);
    }
    return length;
}

u32 XUwachannel_accelerator_Get_c_re_1_1_V_BaseAddress(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_1_V_BASE);
}

u32 XUwachannel_accelerator_Get_c_re_1_1_V_HighAddress(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_1_V_HIGH);
}

u32 XUwachannel_accelerator_Get_c_re_1_1_V_TotalBytes(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_1_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_1_V_BASE + 1);
}

u32 XUwachannel_accelerator_Get_c_re_1_1_V_BitWidth(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_WIDTH_C_RE_1_1_V;
}

u32 XUwachannel_accelerator_Get_c_re_1_1_V_Depth(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_DEPTH_C_RE_1_1_V;
}

u32 XUwachannel_accelerator_Write_c_re_1_1_V_Words(XUwachannel_accelerator *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_1_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_1_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_1_V_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XUwachannel_accelerator_Read_c_re_1_1_V_Words(XUwachannel_accelerator *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_1_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_1_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_1_V_BASE + (offset + i)*4);
    }
    return length;
}

u32 XUwachannel_accelerator_Write_c_re_1_1_V_Bytes(XUwachannel_accelerator *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_1_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_1_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_1_V_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XUwachannel_accelerator_Read_c_re_1_1_V_Bytes(XUwachannel_accelerator *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_1_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_1_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_1_V_BASE + offset + i);
    }
    return length;
}

u32 XUwachannel_accelerator_Get_c_re_1_2_V_BaseAddress(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_2_V_BASE);
}

u32 XUwachannel_accelerator_Get_c_re_1_2_V_HighAddress(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_2_V_HIGH);
}

u32 XUwachannel_accelerator_Get_c_re_1_2_V_TotalBytes(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_2_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_2_V_BASE + 1);
}

u32 XUwachannel_accelerator_Get_c_re_1_2_V_BitWidth(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_WIDTH_C_RE_1_2_V;
}

u32 XUwachannel_accelerator_Get_c_re_1_2_V_Depth(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_DEPTH_C_RE_1_2_V;
}

u32 XUwachannel_accelerator_Write_c_re_1_2_V_Words(XUwachannel_accelerator *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_2_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_2_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_2_V_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XUwachannel_accelerator_Read_c_re_1_2_V_Words(XUwachannel_accelerator *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_2_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_2_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_2_V_BASE + (offset + i)*4);
    }
    return length;
}

u32 XUwachannel_accelerator_Write_c_re_1_2_V_Bytes(XUwachannel_accelerator *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_2_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_2_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_2_V_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XUwachannel_accelerator_Read_c_re_1_2_V_Bytes(XUwachannel_accelerator *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_2_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_2_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_2_V_BASE + offset + i);
    }
    return length;
}

u32 XUwachannel_accelerator_Get_c_re_1_3_V_BaseAddress(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_3_V_BASE);
}

u32 XUwachannel_accelerator_Get_c_re_1_3_V_HighAddress(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_3_V_HIGH);
}

u32 XUwachannel_accelerator_Get_c_re_1_3_V_TotalBytes(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_3_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_3_V_BASE + 1);
}

u32 XUwachannel_accelerator_Get_c_re_1_3_V_BitWidth(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_WIDTH_C_RE_1_3_V;
}

u32 XUwachannel_accelerator_Get_c_re_1_3_V_Depth(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_DEPTH_C_RE_1_3_V;
}

u32 XUwachannel_accelerator_Write_c_re_1_3_V_Words(XUwachannel_accelerator *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_3_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_3_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_3_V_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XUwachannel_accelerator_Read_c_re_1_3_V_Words(XUwachannel_accelerator *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_3_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_3_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_3_V_BASE + (offset + i)*4);
    }
    return length;
}

u32 XUwachannel_accelerator_Write_c_re_1_3_V_Bytes(XUwachannel_accelerator *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_3_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_3_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_3_V_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XUwachannel_accelerator_Read_c_re_1_3_V_Bytes(XUwachannel_accelerator *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_3_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_3_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_1_3_V_BASE + offset + i);
    }
    return length;
}

u32 XUwachannel_accelerator_Get_c_im_1_0_V_BaseAddress(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_0_V_BASE);
}

u32 XUwachannel_accelerator_Get_c_im_1_0_V_HighAddress(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_0_V_HIGH);
}

u32 XUwachannel_accelerator_Get_c_im_1_0_V_TotalBytes(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_0_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_0_V_BASE + 1);
}

u32 XUwachannel_accelerator_Get_c_im_1_0_V_BitWidth(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_WIDTH_C_IM_1_0_V;
}

u32 XUwachannel_accelerator_Get_c_im_1_0_V_Depth(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_DEPTH_C_IM_1_0_V;
}

u32 XUwachannel_accelerator_Write_c_im_1_0_V_Words(XUwachannel_accelerator *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_0_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_0_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_0_V_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XUwachannel_accelerator_Read_c_im_1_0_V_Words(XUwachannel_accelerator *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_0_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_0_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_0_V_BASE + (offset + i)*4);
    }
    return length;
}

u32 XUwachannel_accelerator_Write_c_im_1_0_V_Bytes(XUwachannel_accelerator *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_0_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_0_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_0_V_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XUwachannel_accelerator_Read_c_im_1_0_V_Bytes(XUwachannel_accelerator *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_0_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_0_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_0_V_BASE + offset + i);
    }
    return length;
}

u32 XUwachannel_accelerator_Get_c_im_1_1_V_BaseAddress(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_1_V_BASE);
}

u32 XUwachannel_accelerator_Get_c_im_1_1_V_HighAddress(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_1_V_HIGH);
}

u32 XUwachannel_accelerator_Get_c_im_1_1_V_TotalBytes(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_1_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_1_V_BASE + 1);
}

u32 XUwachannel_accelerator_Get_c_im_1_1_V_BitWidth(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_WIDTH_C_IM_1_1_V;
}

u32 XUwachannel_accelerator_Get_c_im_1_1_V_Depth(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_DEPTH_C_IM_1_1_V;
}

u32 XUwachannel_accelerator_Write_c_im_1_1_V_Words(XUwachannel_accelerator *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_1_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_1_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_1_V_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XUwachannel_accelerator_Read_c_im_1_1_V_Words(XUwachannel_accelerator *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_1_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_1_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_1_V_BASE + (offset + i)*4);
    }
    return length;
}

u32 XUwachannel_accelerator_Write_c_im_1_1_V_Bytes(XUwachannel_accelerator *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_1_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_1_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_1_V_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XUwachannel_accelerator_Read_c_im_1_1_V_Bytes(XUwachannel_accelerator *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_1_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_1_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_1_V_BASE + offset + i);
    }
    return length;
}

u32 XUwachannel_accelerator_Get_c_im_1_2_V_BaseAddress(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_2_V_BASE);
}

u32 XUwachannel_accelerator_Get_c_im_1_2_V_HighAddress(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_2_V_HIGH);
}

u32 XUwachannel_accelerator_Get_c_im_1_2_V_TotalBytes(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_2_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_2_V_BASE + 1);
}

u32 XUwachannel_accelerator_Get_c_im_1_2_V_BitWidth(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_WIDTH_C_IM_1_2_V;
}

u32 XUwachannel_accelerator_Get_c_im_1_2_V_Depth(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_DEPTH_C_IM_1_2_V;
}

u32 XUwachannel_accelerator_Write_c_im_1_2_V_Words(XUwachannel_accelerator *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_2_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_2_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_2_V_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XUwachannel_accelerator_Read_c_im_1_2_V_Words(XUwachannel_accelerator *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_2_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_2_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_2_V_BASE + (offset + i)*4);
    }
    return length;
}

u32 XUwachannel_accelerator_Write_c_im_1_2_V_Bytes(XUwachannel_accelerator *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_2_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_2_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_2_V_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XUwachannel_accelerator_Read_c_im_1_2_V_Bytes(XUwachannel_accelerator *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_2_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_2_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_2_V_BASE + offset + i);
    }
    return length;
}

u32 XUwachannel_accelerator_Get_c_im_1_3_V_BaseAddress(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_3_V_BASE);
}

u32 XUwachannel_accelerator_Get_c_im_1_3_V_HighAddress(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_3_V_HIGH);
}

u32 XUwachannel_accelerator_Get_c_im_1_3_V_TotalBytes(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_3_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_3_V_BASE + 1);
}

u32 XUwachannel_accelerator_Get_c_im_1_3_V_BitWidth(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_WIDTH_C_IM_1_3_V;
}

u32 XUwachannel_accelerator_Get_c_im_1_3_V_Depth(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_DEPTH_C_IM_1_3_V;
}

u32 XUwachannel_accelerator_Write_c_im_1_3_V_Words(XUwachannel_accelerator *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_3_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_3_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_3_V_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XUwachannel_accelerator_Read_c_im_1_3_V_Words(XUwachannel_accelerator *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_3_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_3_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_3_V_BASE + (offset + i)*4);
    }
    return length;
}

u32 XUwachannel_accelerator_Write_c_im_1_3_V_Bytes(XUwachannel_accelerator *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_3_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_3_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_3_V_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XUwachannel_accelerator_Read_c_im_1_3_V_Bytes(XUwachannel_accelerator *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_3_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_3_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_1_3_V_BASE + offset + i);
    }
    return length;
}

u32 XUwachannel_accelerator_Get_c_re_2_0_V_BaseAddress(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_0_V_BASE);
}

u32 XUwachannel_accelerator_Get_c_re_2_0_V_HighAddress(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_0_V_HIGH);
}

u32 XUwachannel_accelerator_Get_c_re_2_0_V_TotalBytes(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_0_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_0_V_BASE + 1);
}

u32 XUwachannel_accelerator_Get_c_re_2_0_V_BitWidth(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_WIDTH_C_RE_2_0_V;
}

u32 XUwachannel_accelerator_Get_c_re_2_0_V_Depth(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_DEPTH_C_RE_2_0_V;
}

u32 XUwachannel_accelerator_Write_c_re_2_0_V_Words(XUwachannel_accelerator *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_0_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_0_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_0_V_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XUwachannel_accelerator_Read_c_re_2_0_V_Words(XUwachannel_accelerator *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_0_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_0_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_0_V_BASE + (offset + i)*4);
    }
    return length;
}

u32 XUwachannel_accelerator_Write_c_re_2_0_V_Bytes(XUwachannel_accelerator *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_0_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_0_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_0_V_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XUwachannel_accelerator_Read_c_re_2_0_V_Bytes(XUwachannel_accelerator *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_0_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_0_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_0_V_BASE + offset + i);
    }
    return length;
}

u32 XUwachannel_accelerator_Get_c_re_2_1_V_BaseAddress(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_1_V_BASE);
}

u32 XUwachannel_accelerator_Get_c_re_2_1_V_HighAddress(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_1_V_HIGH);
}

u32 XUwachannel_accelerator_Get_c_re_2_1_V_TotalBytes(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_1_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_1_V_BASE + 1);
}

u32 XUwachannel_accelerator_Get_c_re_2_1_V_BitWidth(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_WIDTH_C_RE_2_1_V;
}

u32 XUwachannel_accelerator_Get_c_re_2_1_V_Depth(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_DEPTH_C_RE_2_1_V;
}

u32 XUwachannel_accelerator_Write_c_re_2_1_V_Words(XUwachannel_accelerator *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_1_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_1_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_1_V_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XUwachannel_accelerator_Read_c_re_2_1_V_Words(XUwachannel_accelerator *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_1_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_1_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_1_V_BASE + (offset + i)*4);
    }
    return length;
}

u32 XUwachannel_accelerator_Write_c_re_2_1_V_Bytes(XUwachannel_accelerator *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_1_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_1_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_1_V_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XUwachannel_accelerator_Read_c_re_2_1_V_Bytes(XUwachannel_accelerator *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_1_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_1_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_1_V_BASE + offset + i);
    }
    return length;
}

u32 XUwachannel_accelerator_Get_c_re_2_2_V_BaseAddress(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_2_V_BASE);
}

u32 XUwachannel_accelerator_Get_c_re_2_2_V_HighAddress(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_2_V_HIGH);
}

u32 XUwachannel_accelerator_Get_c_re_2_2_V_TotalBytes(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_2_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_2_V_BASE + 1);
}

u32 XUwachannel_accelerator_Get_c_re_2_2_V_BitWidth(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_WIDTH_C_RE_2_2_V;
}

u32 XUwachannel_accelerator_Get_c_re_2_2_V_Depth(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_DEPTH_C_RE_2_2_V;
}

u32 XUwachannel_accelerator_Write_c_re_2_2_V_Words(XUwachannel_accelerator *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_2_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_2_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_2_V_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XUwachannel_accelerator_Read_c_re_2_2_V_Words(XUwachannel_accelerator *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_2_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_2_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_2_V_BASE + (offset + i)*4);
    }
    return length;
}

u32 XUwachannel_accelerator_Write_c_re_2_2_V_Bytes(XUwachannel_accelerator *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_2_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_2_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_2_V_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XUwachannel_accelerator_Read_c_re_2_2_V_Bytes(XUwachannel_accelerator *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_2_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_2_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_2_V_BASE + offset + i);
    }
    return length;
}

u32 XUwachannel_accelerator_Get_c_re_2_3_V_BaseAddress(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_3_V_BASE);
}

u32 XUwachannel_accelerator_Get_c_re_2_3_V_HighAddress(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_3_V_HIGH);
}

u32 XUwachannel_accelerator_Get_c_re_2_3_V_TotalBytes(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_3_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_3_V_BASE + 1);
}

u32 XUwachannel_accelerator_Get_c_re_2_3_V_BitWidth(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_WIDTH_C_RE_2_3_V;
}

u32 XUwachannel_accelerator_Get_c_re_2_3_V_Depth(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_DEPTH_C_RE_2_3_V;
}

u32 XUwachannel_accelerator_Write_c_re_2_3_V_Words(XUwachannel_accelerator *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_3_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_3_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_3_V_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XUwachannel_accelerator_Read_c_re_2_3_V_Words(XUwachannel_accelerator *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_3_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_3_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_3_V_BASE + (offset + i)*4);
    }
    return length;
}

u32 XUwachannel_accelerator_Write_c_re_2_3_V_Bytes(XUwachannel_accelerator *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_3_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_3_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_3_V_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XUwachannel_accelerator_Read_c_re_2_3_V_Bytes(XUwachannel_accelerator *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_3_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_3_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_RE_2_3_V_BASE + offset + i);
    }
    return length;
}

u32 XUwachannel_accelerator_Get_c_im_2_0_V_BaseAddress(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_0_V_BASE);
}

u32 XUwachannel_accelerator_Get_c_im_2_0_V_HighAddress(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_0_V_HIGH);
}

u32 XUwachannel_accelerator_Get_c_im_2_0_V_TotalBytes(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_0_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_0_V_BASE + 1);
}

u32 XUwachannel_accelerator_Get_c_im_2_0_V_BitWidth(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_WIDTH_C_IM_2_0_V;
}

u32 XUwachannel_accelerator_Get_c_im_2_0_V_Depth(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_DEPTH_C_IM_2_0_V;
}

u32 XUwachannel_accelerator_Write_c_im_2_0_V_Words(XUwachannel_accelerator *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_0_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_0_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_0_V_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XUwachannel_accelerator_Read_c_im_2_0_V_Words(XUwachannel_accelerator *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_0_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_0_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_0_V_BASE + (offset + i)*4);
    }
    return length;
}

u32 XUwachannel_accelerator_Write_c_im_2_0_V_Bytes(XUwachannel_accelerator *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_0_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_0_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_0_V_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XUwachannel_accelerator_Read_c_im_2_0_V_Bytes(XUwachannel_accelerator *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_0_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_0_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_0_V_BASE + offset + i);
    }
    return length;
}

u32 XUwachannel_accelerator_Get_c_im_2_1_V_BaseAddress(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_1_V_BASE);
}

u32 XUwachannel_accelerator_Get_c_im_2_1_V_HighAddress(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_1_V_HIGH);
}

u32 XUwachannel_accelerator_Get_c_im_2_1_V_TotalBytes(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_1_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_1_V_BASE + 1);
}

u32 XUwachannel_accelerator_Get_c_im_2_1_V_BitWidth(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_WIDTH_C_IM_2_1_V;
}

u32 XUwachannel_accelerator_Get_c_im_2_1_V_Depth(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_DEPTH_C_IM_2_1_V;
}

u32 XUwachannel_accelerator_Write_c_im_2_1_V_Words(XUwachannel_accelerator *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_1_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_1_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_1_V_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XUwachannel_accelerator_Read_c_im_2_1_V_Words(XUwachannel_accelerator *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_1_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_1_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_1_V_BASE + (offset + i)*4);
    }
    return length;
}

u32 XUwachannel_accelerator_Write_c_im_2_1_V_Bytes(XUwachannel_accelerator *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_1_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_1_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_1_V_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XUwachannel_accelerator_Read_c_im_2_1_V_Bytes(XUwachannel_accelerator *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_1_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_1_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_1_V_BASE + offset + i);
    }
    return length;
}

u32 XUwachannel_accelerator_Get_c_im_2_2_V_BaseAddress(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_2_V_BASE);
}

u32 XUwachannel_accelerator_Get_c_im_2_2_V_HighAddress(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_2_V_HIGH);
}

u32 XUwachannel_accelerator_Get_c_im_2_2_V_TotalBytes(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_2_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_2_V_BASE + 1);
}

u32 XUwachannel_accelerator_Get_c_im_2_2_V_BitWidth(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_WIDTH_C_IM_2_2_V;
}

u32 XUwachannel_accelerator_Get_c_im_2_2_V_Depth(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_DEPTH_C_IM_2_2_V;
}

u32 XUwachannel_accelerator_Write_c_im_2_2_V_Words(XUwachannel_accelerator *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_2_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_2_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_2_V_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XUwachannel_accelerator_Read_c_im_2_2_V_Words(XUwachannel_accelerator *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_2_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_2_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_2_V_BASE + (offset + i)*4);
    }
    return length;
}

u32 XUwachannel_accelerator_Write_c_im_2_2_V_Bytes(XUwachannel_accelerator *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_2_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_2_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_2_V_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XUwachannel_accelerator_Read_c_im_2_2_V_Bytes(XUwachannel_accelerator *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_2_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_2_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_2_V_BASE + offset + i);
    }
    return length;
}

u32 XUwachannel_accelerator_Get_c_im_2_3_V_BaseAddress(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_3_V_BASE);
}

u32 XUwachannel_accelerator_Get_c_im_2_3_V_HighAddress(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_3_V_HIGH);
}

u32 XUwachannel_accelerator_Get_c_im_2_3_V_TotalBytes(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_3_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_3_V_BASE + 1);
}

u32 XUwachannel_accelerator_Get_c_im_2_3_V_BitWidth(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_WIDTH_C_IM_2_3_V;
}

u32 XUwachannel_accelerator_Get_c_im_2_3_V_Depth(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_DEPTH_C_IM_2_3_V;
}

u32 XUwachannel_accelerator_Write_c_im_2_3_V_Words(XUwachannel_accelerator *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_3_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_3_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_3_V_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XUwachannel_accelerator_Read_c_im_2_3_V_Words(XUwachannel_accelerator *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_3_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_3_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_3_V_BASE + (offset + i)*4);
    }
    return length;
}

u32 XUwachannel_accelerator_Write_c_im_2_3_V_Bytes(XUwachannel_accelerator *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_3_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_3_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_3_V_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XUwachannel_accelerator_Read_c_im_2_3_V_Bytes(XUwachannel_accelerator *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_3_V_HIGH - XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_3_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Uwachannel_ctrl_BaseAddress + XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_C_IM_2_3_V_BASE + offset + i);
    }
    return length;
}

void XUwachannel_accelerator_InterruptGlobalEnable(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XUwachannel_accelerator_WriteReg(InstancePtr->Uwachannel_ctrl_BaseAddress, XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_GIE, 1);
}

void XUwachannel_accelerator_InterruptGlobalDisable(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XUwachannel_accelerator_WriteReg(InstancePtr->Uwachannel_ctrl_BaseAddress, XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_GIE, 0);
}

void XUwachannel_accelerator_InterruptEnable(XUwachannel_accelerator *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XUwachannel_accelerator_ReadReg(InstancePtr->Uwachannel_ctrl_BaseAddress, XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_IER);
    XUwachannel_accelerator_WriteReg(InstancePtr->Uwachannel_ctrl_BaseAddress, XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_IER, Register | Mask);
}

void XUwachannel_accelerator_InterruptDisable(XUwachannel_accelerator *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XUwachannel_accelerator_ReadReg(InstancePtr->Uwachannel_ctrl_BaseAddress, XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_IER);
    XUwachannel_accelerator_WriteReg(InstancePtr->Uwachannel_ctrl_BaseAddress, XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_IER, Register & (~Mask));
}

void XUwachannel_accelerator_InterruptClear(XUwachannel_accelerator *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XUwachannel_accelerator_WriteReg(InstancePtr->Uwachannel_ctrl_BaseAddress, XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_ISR, Mask);
}

u32 XUwachannel_accelerator_InterruptGetEnabled(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XUwachannel_accelerator_ReadReg(InstancePtr->Uwachannel_ctrl_BaseAddress, XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_IER);
}

u32 XUwachannel_accelerator_InterruptGetStatus(XUwachannel_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XUwachannel_accelerator_ReadReg(InstancePtr->Uwachannel_ctrl_BaseAddress, XUWACHANNEL_ACCELERATOR_UWACHANNEL_CTRL_ADDR_ISR);
}

